// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lewisgibson/go-steam/client (interfaces: Identity)
//
// Generated by this command:
//
//	mockgen -destination=mock_identity_test.go -package=client_test . Identity
//

// Package client_test is a generated GoMock package.
package client_test

import (
	reflect "reflect"

	steamid "github.com/lewisgibson/go-steam/steamid"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentity is a mock of Identity interface.
type MockIdentity struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityMockRecorder
	isgomock struct{}
}

// MockIdentityMockRecorder is the mock recorder for MockIdentity.
type MockIdentityMockRecorder struct {
	mock *MockIdentity
}

// NewMockIdentity creates a new mock instance.
func NewMockIdentity(ctrl *gomock.Controller) *MockIdentity {
	mock := &MockIdentity{ctrl: ctrl}
	mock.recorder = &MockIdentityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentity) EXPECT() *MockIdentityMockRecorder {
	return m.recorder
}

// RefreshToken mocks base method.
func (m *MockIdentity) RefreshToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockIdentityMockRecorder) RefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockIdentity)(nil).RefreshToken))
}

// SteamID mocks base method.
func (m *MockIdentity) SteamID() steamid.SteamID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SteamID")
	ret0, _ := ret[0].(steamid.SteamID)
	return ret0
}

// SteamID indicates an expected call of SteamID.
func (mr *MockIdentityMockRecorder) SteamID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SteamID", reflect.TypeOf((*MockIdentity)(nil).SteamID))
}
