// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EMsg.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EMsg) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EClientPersonaStateFlag.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EClientPersonaStateFlag) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EMsgClanAccountFlags.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EMsgClanAccountFlags) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESteamReviewScore.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESteamReviewScore) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECodecUsagePlatform.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECodecUsagePlatform) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ECodecUsageReason.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ECodecUsageReason) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
