// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EDisplayStatus.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EDisplayStatus) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAppCloudStatus.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAppCloudStatus) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAppControllerSupportLevel.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAppControllerSupportLevel) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAppGamepadGyroTrackpadSupportLevel.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAppGamepadGyroTrackpadSupportLevel) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAppHDRSupport.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAppHDRSupport) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
