// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EFamilyGroupRole.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EFamilyGroupRole) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EFamilyGroupsTwoFactorMethod.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EFamilyGroupsTwoFactorMethod) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPurchaseRequestAction.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPurchaseRequestAction) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EFamilyGroupChangeLogType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EFamilyGroupChangeLogType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESharedLibraryExcludeReason.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESharedLibraryExcludeReason) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
