// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EMarketingMessageType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EMarketingMessageType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EMarketingMessageVisibility.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EMarketingMessageVisibility) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EMarketingMessageAssociationType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EMarketingMessageAssociationType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EMarketingMessageTemplateType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EMarketingMessageTemplateType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EMarketingMessageClickLocation.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EMarketingMessageClickLocation) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EMarketingMessageLookupType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EMarketingMessageLookupType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
