// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EClientNotificationType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EClientNotificationType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ESystemUpdateNotificationType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ESystemUpdateNotificationType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EGameRecordingErrorType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EGameRecordingErrorType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
