// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for ERemoteClientBroadcastMsg.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ERemoteClientBroadcastMsg) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ERemoteClientService.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ERemoteClientService) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EVRLinkCaps.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EVRLinkCaps) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ERemoteDeviceAuthorizationResult.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ERemoteDeviceAuthorizationResult) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamDeviceFormFactor.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamDeviceFormFactor) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamTransport.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamTransport) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EStreamInterface.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStreamInterface) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ERemoteDeviceStreamingResult.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ERemoteDeviceStreamingResult) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
