// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: steammessages_clientserver_ufs.proto

package steam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgClientUFSGetUGCDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hcontent      *uint64                `protobuf:"fixed64,1,opt,name=hcontent,def=18446744073709551615" json:"hcontent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientUFSGetUGCDetails fields.
const (
	Default_CMsgClientUFSGetUGCDetails_Hcontent = uint64(18446744073709551615)
)

func (x *CMsgClientUFSGetUGCDetails) Reset() {
	*x = CMsgClientUFSGetUGCDetails{}
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientUFSGetUGCDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientUFSGetUGCDetails) ProtoMessage() {}

func (x *CMsgClientUFSGetUGCDetails) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientUFSGetUGCDetails.ProtoReflect.Descriptor instead.
func (*CMsgClientUFSGetUGCDetails) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_ufs_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgClientUFSGetUGCDetails) GetHcontent() uint64 {
	if x != nil && x.Hcontent != nil {
		return *x.Hcontent
	}
	return Default_CMsgClientUFSGetUGCDetails_Hcontent
}

type CMsgClientUFSGetUGCDetailsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Eresult            *int32                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	Url                *string                `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	AppId              *uint32                `protobuf:"varint,3,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	Filename           *string                `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
	SteamidCreator     *uint64                `protobuf:"fixed64,5,opt,name=steamid_creator,json=steamidCreator" json:"steamid_creator,omitempty"`
	FileSize           *uint32                `protobuf:"varint,6,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
	CompressedFileSize *uint32                `protobuf:"varint,7,opt,name=compressed_file_size,json=compressedFileSize" json:"compressed_file_size,omitempty"`
	RangecheckHost     *string                `protobuf:"bytes,8,opt,name=rangecheck_host,json=rangecheckHost" json:"rangecheck_host,omitempty"`
	FileEncodedSha1    *string                `protobuf:"bytes,9,opt,name=file_encoded_sha1,json=fileEncodedSha1" json:"file_encoded_sha1,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for CMsgClientUFSGetUGCDetailsResponse fields.
const (
	Default_CMsgClientUFSGetUGCDetailsResponse_Eresult = int32(2)
)

func (x *CMsgClientUFSGetUGCDetailsResponse) Reset() {
	*x = CMsgClientUFSGetUGCDetailsResponse{}
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientUFSGetUGCDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientUFSGetUGCDetailsResponse) ProtoMessage() {}

func (x *CMsgClientUFSGetUGCDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientUFSGetUGCDetailsResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientUFSGetUGCDetailsResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_ufs_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgClientUFSGetUGCDetailsResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientUFSGetUGCDetailsResponse_Eresult
}

func (x *CMsgClientUFSGetUGCDetailsResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *CMsgClientUFSGetUGCDetailsResponse) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientUFSGetUGCDetailsResponse) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

func (x *CMsgClientUFSGetUGCDetailsResponse) GetSteamidCreator() uint64 {
	if x != nil && x.SteamidCreator != nil {
		return *x.SteamidCreator
	}
	return 0
}

func (x *CMsgClientUFSGetUGCDetailsResponse) GetFileSize() uint32 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *CMsgClientUFSGetUGCDetailsResponse) GetCompressedFileSize() uint32 {
	if x != nil && x.CompressedFileSize != nil {
		return *x.CompressedFileSize
	}
	return 0
}

func (x *CMsgClientUFSGetUGCDetailsResponse) GetRangecheckHost() string {
	if x != nil && x.RangecheckHost != nil {
		return *x.RangecheckHost
	}
	return ""
}

func (x *CMsgClientUFSGetUGCDetailsResponse) GetFileEncodedSha1() string {
	if x != nil && x.FileEncodedSha1 != nil {
		return *x.FileEncodedSha1
	}
	return ""
}

type CMsgClientUFSGetSingleFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         *uint32                `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	FileName      *string                `protobuf:"bytes,2,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientUFSGetSingleFileInfo) Reset() {
	*x = CMsgClientUFSGetSingleFileInfo{}
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientUFSGetSingleFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientUFSGetSingleFileInfo) ProtoMessage() {}

func (x *CMsgClientUFSGetSingleFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientUFSGetSingleFileInfo.ProtoReflect.Descriptor instead.
func (*CMsgClientUFSGetSingleFileInfo) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_ufs_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgClientUFSGetSingleFileInfo) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientUFSGetSingleFileInfo) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

type CMsgClientUFSGetSingleFileInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Eresult          *int32                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	AppId            *uint32                `protobuf:"varint,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	FileName         *string                `protobuf:"bytes,3,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	ShaFile          []byte                 `protobuf:"bytes,4,opt,name=sha_file,json=shaFile" json:"sha_file,omitempty"`
	TimeStamp        *uint64                `protobuf:"varint,5,opt,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	RawFileSize      *uint32                `protobuf:"varint,6,opt,name=raw_file_size,json=rawFileSize" json:"raw_file_size,omitempty"`
	IsExplicitDelete *bool                  `protobuf:"varint,7,opt,name=is_explicit_delete,json=isExplicitDelete" json:"is_explicit_delete,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for CMsgClientUFSGetSingleFileInfoResponse fields.
const (
	Default_CMsgClientUFSGetSingleFileInfoResponse_Eresult = int32(2)
)

func (x *CMsgClientUFSGetSingleFileInfoResponse) Reset() {
	*x = CMsgClientUFSGetSingleFileInfoResponse{}
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientUFSGetSingleFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientUFSGetSingleFileInfoResponse) ProtoMessage() {}

func (x *CMsgClientUFSGetSingleFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientUFSGetSingleFileInfoResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientUFSGetSingleFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_ufs_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgClientUFSGetSingleFileInfoResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientUFSGetSingleFileInfoResponse_Eresult
}

func (x *CMsgClientUFSGetSingleFileInfoResponse) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientUFSGetSingleFileInfoResponse) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *CMsgClientUFSGetSingleFileInfoResponse) GetShaFile() []byte {
	if x != nil {
		return x.ShaFile
	}
	return nil
}

func (x *CMsgClientUFSGetSingleFileInfoResponse) GetTimeStamp() uint64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

func (x *CMsgClientUFSGetSingleFileInfoResponse) GetRawFileSize() uint32 {
	if x != nil && x.RawFileSize != nil {
		return *x.RawFileSize
	}
	return 0
}

func (x *CMsgClientUFSGetSingleFileInfoResponse) GetIsExplicitDelete() bool {
	if x != nil && x.IsExplicitDelete != nil {
		return *x.IsExplicitDelete
	}
	return false
}

type CMsgClientUFSShareFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         *uint32                `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	FileName      *string                `protobuf:"bytes,2,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientUFSShareFile) Reset() {
	*x = CMsgClientUFSShareFile{}
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientUFSShareFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientUFSShareFile) ProtoMessage() {}

func (x *CMsgClientUFSShareFile) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientUFSShareFile.ProtoReflect.Descriptor instead.
func (*CMsgClientUFSShareFile) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_ufs_proto_rawDescGZIP(), []int{4}
}

func (x *CMsgClientUFSShareFile) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientUFSShareFile) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

type CMsgClientUFSShareFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eresult       *int32                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	Hcontent      *uint64                `protobuf:"fixed64,2,opt,name=hcontent,def=18446744073709551615" json:"hcontent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientUFSShareFileResponse fields.
const (
	Default_CMsgClientUFSShareFileResponse_Eresult  = int32(2)
	Default_CMsgClientUFSShareFileResponse_Hcontent = uint64(18446744073709551615)
)

func (x *CMsgClientUFSShareFileResponse) Reset() {
	*x = CMsgClientUFSShareFileResponse{}
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientUFSShareFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientUFSShareFileResponse) ProtoMessage() {}

func (x *CMsgClientUFSShareFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_ufs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientUFSShareFileResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientUFSShareFileResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_ufs_proto_rawDescGZIP(), []int{5}
}

func (x *CMsgClientUFSShareFileResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientUFSShareFileResponse_Eresult
}

func (x *CMsgClientUFSShareFileResponse) GetHcontent() uint64 {
	if x != nil && x.Hcontent != nil {
		return *x.Hcontent
	}
	return Default_CMsgClientUFSShareFileResponse_Hcontent
}

var File_steammessages_clientserver_ufs_proto protoreflect.FileDescriptor

const file_steammessages_clientserver_ufs_proto_rawDesc = "" +
	"\n" +
	"$steammessages_clientserver_ufs.proto\x1a\x18steammessages_base.proto\"N\n" +
	"\x1aCMsgClientUFSGetUGCDetails\x120\n" +
	"\bhcontent\x18\x01 \x01(\x06:\x1418446744073709551615R\bhcontent\"\xd3\x02\n" +
	"\"CMsgClientUFSGetUGCDetailsResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\rR\x05appId\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12'\n" +
	"\x0fsteamid_creator\x18\x05 \x01(\x06R\x0esteamidCreator\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\rR\bfileSize\x120\n" +
	"\x14compressed_file_size\x18\a \x01(\rR\x12compressedFileSize\x12'\n" +
	"\x0frangecheck_host\x18\b \x01(\tR\x0erangecheckHost\x12*\n" +
	"\x11file_encoded_sha1\x18\t \x01(\tR\x0ffileEncodedSha1\"T\n" +
	"\x1eCMsgClientUFSGetSingleFileInfo\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"\x85\x02\n" +
	"&CMsgClientUFSGetSingleFileInfoResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\rR\x05appId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x19\n" +
	"\bsha_file\x18\x04 \x01(\fR\ashaFile\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\x05 \x01(\x04R\ttimeStamp\x12\"\n" +
	"\rraw_file_size\x18\x06 \x01(\rR\vrawFileSize\x12,\n" +
	"\x12is_explicit_delete\x18\a \x01(\bR\x10isExplicitDelete\"L\n" +
	"\x16CMsgClientUFSShareFile\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"o\n" +
	"\x1eCMsgClientUFSShareFileResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x120\n" +
	"\bhcontent\x18\x02 \x01(\x06:\x1418446744073709551615R\bhcontentB\x05H\x01\x80\x01\x00"

var (
	file_steammessages_clientserver_ufs_proto_rawDescOnce sync.Once
	file_steammessages_clientserver_ufs_proto_rawDescData []byte
)

func file_steammessages_clientserver_ufs_proto_rawDescGZIP() []byte {
	file_steammessages_clientserver_ufs_proto_rawDescOnce.Do(func() {
		file_steammessages_clientserver_ufs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_ufs_proto_rawDesc), len(file_steammessages_clientserver_ufs_proto_rawDesc)))
	})
	return file_steammessages_clientserver_ufs_proto_rawDescData
}

var file_steammessages_clientserver_ufs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_steammessages_clientserver_ufs_proto_goTypes = []any{
	(*CMsgClientUFSGetUGCDetails)(nil),             // 0: CMsgClientUFSGetUGCDetails
	(*CMsgClientUFSGetUGCDetailsResponse)(nil),     // 1: CMsgClientUFSGetUGCDetailsResponse
	(*CMsgClientUFSGetSingleFileInfo)(nil),         // 2: CMsgClientUFSGetSingleFileInfo
	(*CMsgClientUFSGetSingleFileInfoResponse)(nil), // 3: CMsgClientUFSGetSingleFileInfoResponse
	(*CMsgClientUFSShareFile)(nil),                 // 4: CMsgClientUFSShareFile
	(*CMsgClientUFSShareFileResponse)(nil),         // 5: CMsgClientUFSShareFileResponse
}
var file_steammessages_clientserver_ufs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steammessages_clientserver_ufs_proto_init() }
func file_steammessages_clientserver_ufs_proto_init() {
	if File_steammessages_clientserver_ufs_proto != nil {
		return
	}
	file_steammessages_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_ufs_proto_rawDesc), len(file_steammessages_clientserver_ufs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_clientserver_ufs_proto_goTypes,
		DependencyIndexes: file_steammessages_clientserver_ufs_proto_depIdxs,
		MessageInfos:      file_steammessages_clientserver_ufs_proto_msgTypes,
	}.Build()
	File_steammessages_clientserver_ufs_proto = out.File
	file_steammessages_clientserver_ufs_proto_goTypes = nil
	file_steammessages_clientserver_ufs_proto_depIdxs = nil
}
