// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EBanContentCheckResult.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EBanContentCheckResult) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EProtoClanEventType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EProtoClanEventType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for PartnerEventNotificationType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x PartnerEventNotificationType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
