// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EStoreDiscoveryQueueType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EStoreDiscoveryQueueType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPlaytestStatus.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPlaytestStatus) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAppReportType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAppReportType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EUserReviewScorePreference.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EUserReviewScorePreference) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EPartnerLinkTrackingBackfillSource.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EPartnerLinkTrackingBackfillSource) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
