// Code generated by protoc-gen-enums. DO NOT EDIT.

package steam

import (
	"net/url"
	"strconv"
)

// EncodeValues implements the query.Encoder interface for EAuthTokenPlatformType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAuthTokenPlatformType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAuthTokenAppType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAuthTokenAppType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAuthSessionGuardType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAuthSessionGuardType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAuthSessionSecurityHistory.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAuthSessionSecurityHistory) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for ETokenRenewalType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x ETokenRenewalType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAuthenticationType.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAuthenticationType) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAuthTokenState.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAuthTokenState) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}

// EncodeValues implements the query.Encoder interface for EAuthTokenRevokeAction.
// This allows the enum to be encoded as its numerical value in URL parameters.
func (x EAuthTokenRevokeAction) EncodeValues(key string, v *url.Values) error {
	v.Add(key, strconv.FormatInt(int64(x), 10))
	return nil
}
