// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: webuimessages_audio.proto

package steam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CAudio_PlaySpeakerTestOnChannel_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelNum    *int32                 `protobuf:"varint,1,opt,name=channel_num,json=channelNum" json:"channel_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_PlaySpeakerTestOnChannel_Request) Reset() {
	*x = CAudio_PlaySpeakerTestOnChannel_Request{}
	mi := &file_webuimessages_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_PlaySpeakerTestOnChannel_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_PlaySpeakerTestOnChannel_Request) ProtoMessage() {}

func (x *CAudio_PlaySpeakerTestOnChannel_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_PlaySpeakerTestOnChannel_Request.ProtoReflect.Descriptor instead.
func (*CAudio_PlaySpeakerTestOnChannel_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{0}
}

func (x *CAudio_PlaySpeakerTestOnChannel_Request) GetChannelNum() int32 {
	if x != nil && x.ChannelNum != nil {
		return *x.ChannelNum
	}
	return 0
}

type CAudio_PlaySpeakerTestOnChannel_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAudio_PlaySpeakerTestOnChannel_Response) Reset() {
	*x = CAudio_PlaySpeakerTestOnChannel_Response{}
	mi := &file_webuimessages_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAudio_PlaySpeakerTestOnChannel_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAudio_PlaySpeakerTestOnChannel_Response) ProtoMessage() {}

func (x *CAudio_PlaySpeakerTestOnChannel_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAudio_PlaySpeakerTestOnChannel_Response.ProtoReflect.Descriptor instead.
func (*CAudio_PlaySpeakerTestOnChannel_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_audio_proto_rawDescGZIP(), []int{1}
}

func (x *CAudio_PlaySpeakerTestOnChannel_Response) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

var File_webuimessages_audio_proto protoreflect.FileDescriptor

const file_webuimessages_audio_proto_rawDesc = "" +
	"\n" +
	"\x19webuimessages_audio.proto\x1a\x18steammessages_base.proto\x1a\x18webuimessages_base.proto\"J\n" +
	"'CAudio_PlaySpeakerTestOnChannel_Request\x12\x1f\n" +
	"\vchannel_num\x18\x01 \x01(\x05R\n" +
	"channelNum\"D\n" +
	"(CAudio_PlaySpeakerTestOnChannel_Response\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2~\n" +
	"\x05Audio\x12o\n" +
	"\x18PlaySpeakerTestOnChannel\x12(.CAudio_PlaySpeakerTestOnChannel_Request\x1a).CAudio_PlaySpeakerTestOnChannel_Response\x1a\x04\x80\x97\"\x01B\x05H\x01\x80\x01\x01"

var (
	file_webuimessages_audio_proto_rawDescOnce sync.Once
	file_webuimessages_audio_proto_rawDescData []byte
)

func file_webuimessages_audio_proto_rawDescGZIP() []byte {
	file_webuimessages_audio_proto_rawDescOnce.Do(func() {
		file_webuimessages_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webuimessages_audio_proto_rawDesc), len(file_webuimessages_audio_proto_rawDesc)))
	})
	return file_webuimessages_audio_proto_rawDescData
}

var file_webuimessages_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_webuimessages_audio_proto_goTypes = []any{
	(*CAudio_PlaySpeakerTestOnChannel_Request)(nil),  // 0: CAudio_PlaySpeakerTestOnChannel_Request
	(*CAudio_PlaySpeakerTestOnChannel_Response)(nil), // 1: CAudio_PlaySpeakerTestOnChannel_Response
}
var file_webuimessages_audio_proto_depIdxs = []int32{
	0, // 0: Audio.PlaySpeakerTestOnChannel:input_type -> CAudio_PlaySpeakerTestOnChannel_Request
	1, // 1: Audio.PlaySpeakerTestOnChannel:output_type -> CAudio_PlaySpeakerTestOnChannel_Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_webuimessages_audio_proto_init() }
func file_webuimessages_audio_proto_init() {
	if File_webuimessages_audio_proto != nil {
		return
	}
	file_steammessages_base_proto_init()
	file_webuimessages_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webuimessages_audio_proto_rawDesc), len(file_webuimessages_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webuimessages_audio_proto_goTypes,
		DependencyIndexes: file_webuimessages_audio_proto_depIdxs,
		MessageInfos:      file_webuimessages_audio_proto_msgTypes,
	}.Build()
	File_webuimessages_audio_proto = out.File
	file_webuimessages_audio_proto_goTypes = nil
	file_webuimessages_audio_proto_depIdxs = nil
}
